// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdjvrmxogoprczqvlcrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkanZybXhvZ29wcmN6cXZsY3JwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMTczOTksImV4cCI6MjA2Mzc5MzM5OX0.EKrwr4K4EbI1n3eUks9LZGu39hJgPlPuONRMD3S69yw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);